baseURL = "https://moiaune.dev/"
languageCode = "en-us"
title = "moiaune.dev"
theme = "plaintext"
enableGitInfo = true

[markup]
  [markup.highlight]
    codeFences = false

[pagination]
    disableAliases = false
    pagerSize = 10
    path = "page"

[permalinks]
  posts = "/:year/:month/:day/:title/"
