baseURL = "https://moiaune.dev/"
languageCode = "en-us"
title = "moiaune.dev"

PygmentsCodeFences = true
PygmentsUseClasses = true
PygmentsStyle = "fruity"

[markup]
  [markup.highlight]
    tabWidth = 4
    codeFences = true

[params]
  OwnerName = "Mads Moi-Aune"
  Twitter = "kapteindev"

[permalinks]
  posts = "/:year/:month/:day/:title/"
