name = 'plaintext'
license = 'MIT'
licenselink = 'https://github.com/moiaune/plaintext/blob/master/README.md'
description = 'A plaintext Hugo theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/moiaune/plaintext'

# If you have a running demo of the theme
demosite = 'https://moiaune.github.io/plaintext'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Mads Moi-Aune'
  homepage = 'https://moiaune.dev'
